repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        entry: black -l 79 -S
        exclude: ^(tests/|\.venv/|\.tox/|\.git/|\.mypy_cache/|_build/|buck-out/|build/|dist/|node_modules/|\.eggs/|\.pytest_cache/|\.cache/|\.ropeproject/|\.mypy_cache/|\.vscode/|\.idea/|\.ipynb_checkpoints/|\.DS_Store/|\.coverage/|\.coverage.*)
        language_version: python3.8
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--config=.flake8]
        additional_dependencies:
          - flake8-bugbear
          - flake8-return
          - flake8-comprehensions
          - flake8-pie
          - flake8-print
          - flake8-simplify
          - flake8-variables-names
          - pep8-naming
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-byte-order-marker
      - id: check-ast
